load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "lookaside",
    srcs = ["lookaside.go"],
    importpath = "peridot.resf.org/peridot/lookaside",
    visibility = ["//visibility:public"],
)
