---
# Get this from Github
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: prow
#   name: github-token
# stringData:
#   cert: <<insert-downloaded-cert-here>>
#   appid: <<insert-the-app-id-here>>
# ---
# Generate this manually
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: prow
#   name: hmac-token
# stringData:
#   # Generate via `openssl rand -hex 20`. This is the secret used in the GitHub webhook configuration
#   hmac: << insert-hmac-token-here >>
apiVersion: v1
kind: Secret
metadata:
  namespace: prow
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "us-east-2"
    }
---
apiVersion: v1
kind: Secret
metadata:
  namespace: test-pods
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "us-east-2"
    }
